"""add core schema

Revision ID: ace583ba4dd0
Revises: 
Create Date: 2026-08-20 17:00:58.500916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ace583ba4dd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_unions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_unions'))
    )
    op.create_table('member_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_profiles')),
    sa.UniqueConstraint('member_id', 'version', name='uq_member_profiles_member_id_version')
    )
    op.create_index(op.f('ix_member_profiles_member_id'), 'member_profiles', ['member_id'], unique=False)
    op.create_index('uq_member_profiles_one_latest_per_member', 'member_profiles', ['member_id'], unique=True, postgresql_where=sa.text('is_latest'))
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_union_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['credit_union_id'], ['credit_unions.id'], name=op.f('fk_products_credit_union_id_credit_unions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_credit_union_id'), 'products', ['credit_union_id'], unique=False)
    op.create_table('rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_union_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_union_id'], ['credit_unions.id'], name=op.f('fk_rulesets_credit_union_id_credit_unions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rulesets')),
    sa.UniqueConstraint('credit_union_id', 'version', name='uq_rulesets_credit_union_id_version')
    )
    op.create_index(op.f('ix_rulesets_credit_union_id'), 'rulesets', ['credit_union_id'], unique=False)
    op.create_index('uq_rulesets_one_latest_per_credit_union', 'rulesets', ['credit_union_id'], unique=True, postgresql_where=sa.text('is_latest'))
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_union_id', sa.Integer(), nullable=False),
    sa.Column('profile_version_id', sa.UUID(), nullable=False),
    sa.Column('ruleset_version_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('eligible_product_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_union_id'], ['credit_unions.id'], name=op.f('fk_decisions_credit_union_id_credit_unions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_version_id'], ['member_profiles.id'], name=op.f('fk_decisions_profile_version_id_member_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ruleset_version_id'], ['rulesets.id'], name=op.f('fk_decisions_ruleset_version_id_rulesets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_credit_union_id'), 'decisions', ['credit_union_id'], unique=False)
    op.create_index('ix_decisions_credit_union_id_created_at', 'decisions', ['credit_union_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decisions_profile_version_id'), 'decisions', ['profile_version_id'], unique=False)
    op.create_index(op.f('ix_decisions_ruleset_version_id'), 'decisions', ['ruleset_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_ruleset_version_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_profile_version_id'), table_name='decisions')
    op.drop_index('ix_decisions_credit_union_id_created_at', table_name='decisions')
    op.drop_index(op.f('ix_decisions_credit_union_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('uq_rulesets_one_latest_per_credit_union', table_name='rulesets', postgresql_where=sa.text('is_latest'))
    op.drop_index(op.f('ix_rulesets_credit_union_id'), table_name='rulesets')
    op.drop_table('rulesets')
    op.drop_index(op.f('ix_products_credit_union_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('uq_member_profiles_one_latest_per_member', table_name='member_profiles', postgresql_where=sa.text('is_latest'))
    op.drop_index(op.f('ix_member_profiles_member_id'), table_name='member_profiles')
    op.drop_table('member_profiles')
    op.drop_table('credit_unions')
    # ### end Alembic commands ###
