"""add unique constraints for idempotent seeding

Revision ID: bbd8d80040e8
Revises: ace583ba4dd0
Create Date: 2026-08-20 17:44:47.620226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bbd8d80040e8'
down_revision: Union[str, None] = 'ace583ba4dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_credit_unions_name'), 'credit_unions', ['name'])
    op.create_unique_constraint('uq_products_credit_union_id_name', 'products', ['credit_union_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_credit_union_id_name', 'products', type_='unique')
    op.drop_constraint(op.f('uq_credit_unions_name'), 'credit_unions', type_='unique')
    # ### end Alembic commands ###
